### ISSUE TITLE
Adding imports to inlined expressions

### ISSUE THREAD

**Issue by ewhauser** [itechart-almakov/convtools#16]
If you want to inline an expression, is there a way to add imports to the generated code? Example:

```python
c({
 "date": c.inline_expr("my_custom_date_formatter({dt})".pass_args(dt=c.item("date")),
}).gen_converter()
```

You cannot add an import directly inline because the value is being assigned. i.e.:

```python
c({
 "date": c.inline_expr("from my_library import my_custom_date_formatter\n 
  my_custom_date_formatter({dt})".pass_args(dt=c.item("date")),
}).gen_converter()
```

Thanks.

**Comment by westandskif** [comment]
Sure!
`c({
    "date": c.inline_expr("{fmt}({dt})".pass_args(
        fmt=my_custom_date_formatter, 
        dt=c.item("date")
    ),
}).gen_converter()`

**Comment by ewhauser** [comment]
Awesome - thanks
