### ISSUE TITLE
Question on empty items

### ISSUE THREAD

**Issue by ewhauser** [itechart-almakov/convtools#17]
Let's say I have a conversion like:

```python
c({
  'address1': c.item('address1'),
  'address2': c.item('address2'),
})
```

and my input can be like:

```python
items = [
{ 'address1': '221B Baker Street' },
{ 'address1': '10 Downing Street', 'address2': 'Suite 100'}
]
```

I can use `c.item('address2', default=None)` to make `address2` be `None`, but what if I don't want the key to be in the resulting conversion at all, i.e.:

```
{ 'address1': '10 Downing Street' }
```

This is a pretty regular occurrence in my data conversions, so having to pipe the output and use a bunch of `c.if`'s ends up being quite verbose.

**Comment by westandskif** [comment]
If we come up with a clear API to define this type of conversion, that would be great! But for the time being, something like the following should work (writing from phone - there may be some typos)
```
c.list_comp(
    c.call_func(
        dict,
        c([
            ("address1", c.item("address1")),
            ("address2", c.item("address2")),
        ]).filter(c.item(1))
    )
)
```

**Comment by ewhauser** [comment]
One idea of the top of my head would be to do:

```
“address2”: c.item(“address2”, default=c.unset())
```

Or something similar.

**Comment by westandskif** [comment]
Now it's possible to have this done with:
```
c({
  'address1': c.item('address1'),
  'address2': c.optional(c.item('address2', default=None)),
}).gen_converter(debug=True)

# or if iterating needed
c.list_comp({
  'address1': c.item('address1'),
  'address2': c.optional(c.item('address2', default=None)),
}).gen_converter(debug=True)

```
`c.optional` supports conditions too - [cheatsheet link](https://convtools.readthedocs.io/en/latest/cheatsheet.html#parametrized-conversion-with-some-baked-in-arguments-and-optional-items) + [doc link](https://convtools.readthedocs.io/en/latest/api_doc.html#ref-c-optionals)
